title: Justice On The Web

permalink: pretty

header_links:
  GitHub: https://github.com/ministryofjustice/justice-on-the-web

defaults:
  -
    scope:
      path: "standards"
    values:
      standard: true
  -
    scope:
      path: "guides"
    values:
      guide: true
  -
    scope:
      path: "runbooks"
    values:
      runbooks: true
