title: Justice On The Web
permalink: pretty
header_links:
  GitHub: https://github.com/ministryofjustice/justice-on-the-web
defaults:
  -
    scope:
      path: "standards"
      type: "pages"
    values:
      standard: true
  -
    scope:
      path: "guides"
      type: "pages"
    values:
      guide: true